version: "3"
services:
  client:
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"

  server:
    build: ./server/
    ports:
      - "5000:5000"
    volumes:
      - ./server:/code
    environment:
      FLASK_ENV: development

  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminprojet
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    restart: always
    ports:
      - 2000:80
    volumes:
      - /sessions